//
//  Constant.swift
//  TMDB
//
//  Created by Tuyen Le on 6/9/20.
//  Copyright © 2020 Tuyen Le. All rights reserved.
//

import Foundation
import UIKit

struct Constant {
    struct Identifier {
        static let previewHeader = "preview header"
        static let preview = "preview"
        static let countryCell = "CountryCell"
        static let languageCell = "LanguageCell"
        static let countrySearch = "CountrySearch"
    }
    struct ViewControllerIdentifier {
        static let tmdbSearchController = "TMDBCountrySearchResultController"
        static let tmdbCountry = "TMDBCountryViewController"
        static let tmdbHome = "TMDBHomeViewController"
        static let tmdbCountryNavigation = "TMDBCountrySettingNavigation"
        static let tmdbLanguageNavigation = "TMDBLanguageSettingNavigation"
    }
    struct Color {
        static let primaryColor = UIColor(displayP3Red: 13/255, green: 37/255, blue: 63/255, alpha: 1)
        static let secondaryColor = UIColor(displayP3Red: 1/255, green: 180/255, blue: 228/255, alpha: 1)
        static let tertiaryColor = UIColor(displayP3Red: 144/255, green: 206/255, blue:  161/255, alpha: 1)
        static let backgroundColor = UIColor(displayP3Red: 235/255, green: 235/255, blue:  240/255, alpha: 1)
        static let tabBarSelectedTextColor = UIColor(displayP3Red: 231/255, green: 232/255, blue:  238/255, alpha: 1)
    }
    struct UserSetting {
        static let language = "language"
        static let region = "region"
        static let country = "country"
        static let imageConfig = "image config"
        static let regionLanguageChange = "Region Language Change"
    }
    static let imageLogo = "TMDB"

    static let countryName = [
        "AF": "Afghanistan",
        "AX": "Aland Islands",
        "AL": "Albania",
        "DZ": "Algeria",
        "AS": "American Samoa",
        "AD": "Andorra",
        "AO": "Angola",
        "AI": "Anguilla",
        "AG": "Antigua and Barbuda",
        "AR": "Argentina",
        "AM": "Armenia",
        "AW": "Aruba",
        "AU": "Australia",
        "AT": "Austria",
        "AZ": "Azerbaijan",
        "BS": "Bahamas",
        "BH": "Bahrain",
        "BD": "Bangladesh",
        "BB": "Barbados",
        "BY": "Belarus",
        "BE": "Belgium",
        "BZ": "Belize",
        "BJ": "Benin",
        "BM": "Bermuda",
        "BT": "Bhutan",
        "BO": "Bolivia",
        "BA": "Bosnia and Herzegovina",
        "BW": "Botswana",
        "BR": "Brazil",
        "IO": "British Indian Ocean Territory",
        "BN": "Brunei",
        "BG": "Bulgaria",
        "BF": "Burkina Faso",
        "BI": "Burundi",
        "KH": "Cambodia",
        "CM": "Cameroon",
        "CA": "Canada",
        "CV": "Cape Verde",
        "KY": "Cayman Islands",
        "CF": "Central African Republic",
        "TD": "Chad",
        "CL": "Chile",
        "CN": "China",
        "CX": "Christmas Island",
        "CO": "Colombia",
        "KM": "Comoros",
        "CG": "Congo",
        "CD": "Democratic Republic of Congo",
        "CK": "Cook Islands",
        "CR": "Costa Rica",
        "HR": "Croatia",
        "CU": "Cuba",
        "CW": "Curacao",
        "CY": "Cyprus",
        "CZ": "Czech Republic",
        "DK": "Denmark",
        "DJ": "Djibouti",
        "DM": "Dominica",
        "DO": "Dominican Republic",
        "EC": "Ecuador",
        "EG": "Egypt",
        "SV": "El Salvador",
        "GQ": "Equatorial Guinea",
        "ER": "Eritrea",
        "EE": "Estonia",
        "ET": "Ethiopia",
        "FK": "Falkland Islands",
        "FO": "Faroe Islands",
        "FJ": "Fiji",
        "FI": "Finland",
        "FR": "France",
        "PF": "French Polynesia",
        "GA": "Gabon",
        "GM": "Gambia",
        "GE": "Georgia",
        "DE": "Germany",
        "GH": "Ghana",
        "GI": "Gibraltar",
        "GR": "Greece",
        "GL": "Greenland",
        "GD": "Grenada",
        "GU": "Guam",
        "GT": "Guatemala",
        "GG": "Guernsey",
        "GN": "Guinea",
        "GW": "Guinea Bissau",
        "GY": "Guyana",
        "HT": "Haiti",
        "VA": "Holy See (Vatican City State)",
        "HN": "Honduras",
        "HK": "Hong Kong",
        "HU": "Hungary",
        "IS": "Iceland",
        "IN": "India",
        "ID": "Indonesia",
        "IR": "Iran",
        "IQ": "Iraq",
        "IE": "Ireland",
        "IM": "Isle of Man",
        "IL": "Israel",
        "IT": "Italy",
        "JM": "Jamaica",
        "JP": "Japan",
        "JE": "Jersey",
        "JO": "Jordan",
        "KZ": "Kazakhstan",
        "KE": "Kenya",
        "KI": "Kiribati",
        "KR": "South Korea",
        "KW": "Kuwait",
        "KG": "Kyrgyzstan",
        "LA": "Laos",
        "LV": "Latvia",
        "LB": "Lebanon",
        "LS": "Lesotho",
        "LR": "Liberia",
        "LY": "Libya",
        "LI": "Liechtenstein",
        "LT": "Lithuania",
        "LU": "Luxembourg",
        "MO": "Macao",
        "MK": "Republic of Macedonia",
        "MG": "Madagascar",
        "MW": "Malawi",
        "MY": "Malaysia",
        "MV": "Maldives",
        "ML": "Mali",
        "MT": "Malta",
        "MH": "Marshall Islands",
        "MQ": "Martinique",
        "MR": "Mauritania",
        "MU": "Mauritius",
        "MX": "Mexico",
        "MD": "Moldova",
        "MC": "Monaco",
        "MN": "Mongolia",
        "ME": "Montenegro",
        "MS": "Montserrat",
        "MA": "Morocco",
        "MZ": "Mozambique",
        "MM": "Myanmar",
        "NA": "Namibia",
        "NR": "Nauru",
        "NP": "Nepal",
        "NL": "Netherlands",
        "NZ": "New Zealand",
        "NI": "Nicaragua",
        "NE": "Niger",
        "NG": "Nigeria",
        "NU": "Niue",
        "NF": "Norfolk Island",
        "MP": "Northern Mariana Islands",
        "NO": "Norway",
        "OM": "Oman",
        "PK": "Pakistan",
        "PW": "Palau",
        "PS": "Palestine",
        "PA": "Panama",
        "PG": "Papua New Guinea",
        "PY": "Paraguay",
        "PE": "Peru",
        "PH": "Philippines",
        "PN": "Pitcairn Islands",
        "PL": "Poland",
        "PT": "Portugal",
        "PR": "Puerto Rico",
        "QA": "Qatar",
        "RO": "Romania",
        "RU": "Russia",
        "RW": "Rwanda",
        "BL": "Saint Barts",
        "KN": "Saint Kitts and Nevis",
        "LC": "Saint Lucia",
        "VC": "Saint Vincent and the Grenadines",
        "WS": "Samoa",
        "SM": "San Marino",
        "ST": "Sao Tome and Principe",
        "SA": "Saudi Arabia",
        "SN": "Senegal",
        "RS": "Serbia",
        "SC": "Seychelles",
        "SL": "Sierra Leone",
        "SG": "Singapore",
        "SX": "Sint Maarten",
        "SK": "Slovakia",
        "SI": "Slovenia",
        "SB": "Solomon Islands",
        "SO": "Somalia",
        "ZA": "South Africa",
        "SS": "South Sudan",
        "ES": "Spain",
        "LK": "Sri Lanka",
        "SD": "Sudan",
        "SR": "Suriname",
        "SZ": "Swaziland",
        "SE": "Sweden",
        "CH": "Switzerland",
        "TW": "Taiwan",
        "TJ": "Tajikistan",
        "TZ": "Tanzania",
        "TH": "Thailand",
        "TL": "East Timor",
        "TG": "Togo",
        "TK": "Tokelau",
        "TO": "Tonga",
        "TT": "Trinidad and Tobago",
        "TN": "Tunisia",
        "TR": "Turkey",
        "TM": "Turkmenistan",
        "TC": "Turks and Caicos Islands",
        "TV": "Tuvalu",
        "UG": "Uganda",
        "UA": "Ukraine",
        "AE": "United Arab Emirates",
        "GB": "United Kingdom",
        "US": "United States of America",
        "UY": "Uruguay",
        "UZ": "Uzbekistan",
        "VU": "Vanuatu",
        "VE": "Venezuela",
        "VN": "Viet Nam",
        "VG": "British Virgin Islands",
        "VI": "Virgin Islands, U.S.",
        "EH": "Western Sahara",
        "YE": "Yemen",
        "ZM": "Zambia",
        "ZW": "Zimbabwe",
    ]
    static let countryCode = [
        "Afghanistan": "AF",
        "Aland Islands": "AX",
        "Albania": "AL",
        "Algeria": "DZ",
        "American Samoa": "AS",
        "Andorra": "AD",
        "Angola": "AO",
        "Anguilla": "AI",
        "Antarctica": "AQ",
        "Antigua and Barbuda": "AG",
        "Argentina": "AR",
        "Armenia": "AM",
        "Aruba": "AW",
        "Australia": "AU",
        "Austria": "AT",
        "Azerbaijan": "AZ",
        "Bahamas": "BS",
        "Bahrain": "BH",
        "Bangladesh": "BD",
        "Barbados": "BB",
        "Belarus": "BY",
        "Belgium": "BE",
        "Belize": "BZ",
        "Benin": "BJ",
        "Bermuda": "BM",
        "Bhutan": "BT",
        "Bolivia":"BO",
        "Bosnia and Herzegovina":"BA",
        "Botswana":"BW",
        "Bouvet Island":"BV",
        "Brazil":"BR",
        "British Indian Ocean Territory":"IO",
        "Bulgaria":"BG",
        "Burkina Faso":"BF",
        "Burundi":"BI",
        "Cambodia":"KH",
        "Cameroon":"CM",
        "Canada":"CA",
        "Cape Verde":"CV",
        "Cayman Islands":"KY",
        "Central African Republic":"CF",
        "Chad":"TD",
        "Chile":"CL",
        "China":"CN",
        "Christmas Island":"CX",
        "Colombia":"CO",
        "Comoros":"KM",
        "Congo":"CG",
        "Democratic Republic of Congo":"CD",
        "Cook Islands":"CK",
        "Costa Rica":"CR",
        "Croatia":"HR",
        "Cuba":"CU",
        "Curacao":"CW",
        "Cyprus":"CY",
        "Czech Republic":"CZ",
        "Denmark":"DK",
        "Djibouti":"DJ",
        "Dominica":"DM",
        "Dominican Republic":"DO",
        "Ecuador":"EC",
        "Egypt":"EG",
        "El Salvador":"SV",
        "Equatorial Guinea":"GQ",
        "Eritrea":"ER",
        "Estonia":"EE",
        "Ethiopia":"ET",
        "Falkland Islands":"FK",
        "Faroe Islands":"FO",
        "Fiji":"FJ",
        "Finland":"FI",
        "France":"FR",
        "French Polynesia":"PF",
        "Gabon":"GA",
        "Gambia":"GM",
        "Georgia":"GE",
        "Germany":"DE",
        "Ghana":"GH",
        "Gibraltar":"GI",
        "Greece":"GR",
        "Greenland":"GL",
        "Grenada":"GD",
        "Guadeloupe":"GP",
        "Guam":"GU",
        "Guatemala":"GT",
        "Guernsey":"GG",
        "Guinea":"GN",
        "Guinea-Bissau":"GW",
        "Guyana":"GY",
        "Haiti":"HT",
        "Holy See (Vatican City State)":"VA",
        "Honduras":"HN",
        "Hong Kong":"HK",
        "Hungary":"HU",
        "Iceland":"IS",
        "India":"IN",
        "Indonesia":"ID",
        "Iran":"IR",
        "Iraq":"IQ",
        "Ireland":"IE",
        "Isle of Man":"IM",
        "Israel":"IL",
        "Italy":"IT",
        "Jamaica":"JM",
        "Japan":"JP",
        "Jersey":"JE",
        "Jordan":"JO",
        "Kazakhstan":"KZ",
        "Kenya":"KE",
        "Kiribati":"KI",
        "South Korea":"KR",
        "Kuwait":"KW",
        "Kyrgyzstan":"KG",
        "Laos":"LA",
        "Latvia":"LV",
        "Lebanon":"LB",
        "Lesotho":"LS",
        "Liberia":"LR",
        "Libya":"LY",
        "Liechtenstein":"LI",
        "Lithuania":"LT",
        "Luxembourg":"LU",
        "Macao":"MO",
        "Republic of Macedonia":"MK",
        "Madagascar":"MG",
        "Malawi":"MW",
        "Malaysia":"MY",
        "Maldives":"MV",
        "Mali":"ML",
        "Malta":"MT",
        "Marshall Islands":"MH",
        "Martinique":"MQ",
        "Mauritania":"MR",
        "Mauritius":"MU",
        "Mayotte":"YT",
        "Mexico":"MX",
        "Moldova":"MD",
        "Monaco":"MC",
        "Mongolia":"MN",
        "Montenegro":"ME",
        "Montserrat":"MS",
        "Morocco":"MA",
        "Mozambique":"MZ",
        "Myanmar":"MM",
        "Namibia":"NA",
        "Nauru":"NR",
        "Nepal":"NP",
        "Netherlands":"NL",
        "New Zealand":"NZ",
        "Nicaragua":"NI",
        "Niger":"NE",
        "Nigeria":"NG",
        "Niue":"NU",
        "Norfolk Island":"NF",
        "Northern Mariana Islands":"MP",
        "Norway":"NO",
        "Oman":"OM",
        "Pakistan":"PK",
        "Palau":"PW",
        "Palestine":"PS",
        "Panama":"PA",
        "Papua New Guinea":"PG",
        "Paraguay":"PY",
        "Peru":"PE",
        "Philippines":"PH",
        "Pitcairn":"PN",
        "Poland":"PL",
        "Portugal":"PT",
        "Puerto Rico":"PR",
        "Qatar":"QA",
        "RÃ©union":"RE",
        "Romania":"RO",
        "Russian Federation":"RU",
        "Rwanda":"RW",
        "Saint Barts":"BL",
        "Saint Kitts and Nevis":"KN",
        "Saint Lucia":"LC",
        "Saint Vincent and the Grenadines":"VC",
        "Samoa":"WS",
        "San Marino":"SM",
        "Sao Tome and Principe":"ST",
        "Saudi Arabia":"SA",
        "Senegal":"SN",
        "Serbia":"RS",
        "Seychelles":"SC",
        "Sierra Leone":"SL",
        "Singapore":"SG",
        "Sint Maarten":"SX",
        "Slovakia":"SK",
        "Slovenia":"SI",
        "Solomon Islands":"SB",
        "Somalia":"SO",
        "South Africa":"ZA",
        "South Sudan":"SS",
        "Spain":"ES",
        "Sri Lanka":"LK",
        "Sudan":"SD",
        "Suriname":"SR",
        "Swaziland":"SZ",
        "Sweden":"SE",
        "Switzerland":"CH",
        "Syrian Arab Republic":"SY",
        "Taiwan: Province of China":"TW",
        "Tajikistan":"TJ",
        "Tanzania":"TZ",
        "Thailand":"TH",
        "East Timor":"TL",
        "Togo":"TG",
        "Tokelau":"TK",
        "Tonga":"TO",
        "Trinidad and Tobago":"TT",
        "Tunisia":"TN",
        "Turkey":"TR",
        "Turkmenistan":"TM",
        "Turks and Caicos Islands":"TC",
        "Tuvalu":"TV",
        "Uganda":"UG",
        "Ukraine":"UA",
        "United Arab Emirates":"AE",
        "United Kingdom":"GB",
        "United States of America":"US",
        "Uruguay":"UY",
        "Uzbekistan":"UZ",
        "Vanuatu":"VU",
        "Venezuela":"VE",
        "Viet Nam":"VN",
        "British Virgin Islands":"VG",
        "Virgin Islands, U.S.":"VI",
        "Western Sahara":"EH",
        "Yemen":"YE",
        "Zambia":"ZM",
        "Zimbabwe":"ZW",
    ]
    static let languages = [
        "Afar": "ab",
        "Abkhazian": "aa",
        "Afrikaans": "af",
        "Akan": "ak",
        "Albanian": "sq",
        "Amharic": "am",
        "Arabic": "ar",
        "Aragonese": "an",
        "Armenian": "hy",
        "Assamese": "as",
        "Avaric": "av",
        "Avestan": "ae",
        "Aymara": "ay",
        "Azerbaijani": "az",
        "Bashkir": "ba",
        "Bambara": "bm",
        "Basque": "eu",
        "Belarusian": "be",
        "Bengali": "bn",
        "Bihari languages": "bh",
        "Bislama": "bi",
        "Bosnian": "bs",
        "Breton": "br",
        "Bulgarian": "bg",
        "Burmese": "my",
        "Catalan; Valencian": "ca",
        "Chamorro": "ch",
        "Chechen": "ce",
        "Chichewa": "ny",
        "Chinese": "zh",
        "Chuvash": "cv",
        "Cornish": "kw",
        "Corsican": "co",
        "Cree": "cr",
        "Croatian": "hr",
        "Czech": "cs",
        "Central Khmer": "km",
        "Danish": "da",
        "Divehi": "dv",
        "Dutch": "nl",
        "Dzongkha": "dz",
        "English": "en",
        "Esperanto": "eo",
        "Estonian": "et",
        "Ewe": "ee",
        "Faroese": "fo",
        "Fijian": "fj",
        "Finish": "fi",
        "French": "fr",
        "Fulah": "ff",
        "Galician": "gl",
        "Georgian": "ka",
        "German": "de",
        "Greek": "el",
        "Guarani": "gn",
        "Gujarati": "gu",
        "Ganda": "lg",
        "Haitian": "ht",
        "Hausa": "ha",
        "Hebrew": "he",
        "Herero": "hz",
        "Hindi": "hi",
        "Hiri Motu": "ho",
        "Hungarian": "hu",
        "Icelandic": "is",
        "Idonesian": "id",
        "Igbo": "ig",
        "Indonesian": "id",
        "Inuktitut": "iu",
        "Japanese": "ja",
        "Javanese": "jv",
        "Kalaallisut": "kl",
        "Kannada": "kn",
        "Kanuri": "kr",
        "Kashmiri": "ks",
        "Kazakh": "kk",
        "Kikuyu": "ki",
        "Kinyarwanda": "rw",
        "Kirghuz": "ky",
        "Komi": "kv",
        "Kongo": "kg",
        "Korean": "ko",
        "Kurdish": "ku",
        "Kuanyama": "kj",
        "Latin": "la",
        "Luxembourgish": "lb",
        "Limburgan": "li",
        "Lingala": "ln",
        "Lao": "lo",
        "Lithuanian": "it",
        "Luba-Katanga": "lu",
        "Lavian": "lv",
        "Manx": "gv",
        "Macedonian": "mk",
        "Malagasy": "mg",
        "Malay": "ms",
        "Malayalam": "ml",
        "Maltese": "mt",
        "Maori": "mi",
        "Marathi": "mr",
        "Marshallese": "mh",
        "Mongolian": "mn",
        "Naru": "na",
        "Navajo": "nv",
        "North Ndebele": "nd",
        "Nepali": "ne",
        "Ndonga": "ng",
        "Norwegian Bokmal": "nb",
        "Norwegian Nynorsk": "nn",
        "Norwegian": "no",
        "Northern Sami": "se",
        "Occitan": "oc",
        "Ojibwa": "oj",
        "Church Slavic": "cu",
        "Oromo": "om",
        "Oriya": "or",
        "Ossetian": "os",
        "Punjabi": "pa",
        "Pali": "pi",
        "Persian": "fa",
        "Polish": "pl",
        "Pashto": "ps",
        "Portuguese": "pt",
        "Quechua": "qu",
        "Romansh": "rm",
        "Rundi": "rn",
        "Romanian": "ro",
        "Russian": "ru",
        "Sichuan Yi": "ii",
        "South Ndebele": "nr",
        "Sanskrit": "sa",
        "Sardinian": "sc",
        "Sindhi": "sd",
        "Samoan": "sm",
        "Sango": "sg",
        "Serbian": "sr",
        "Shona": "sn",
        "Sinhala": "si",
        "Slovak": "sk",
        "Slovenian": "sl",
        "Somali": "so",
        "Southern Sotho": "st",
        "Spanish": "es",
        "Sundanese": "su",
        "Swahili": "sw",
        "Swati": "ss",
        "Swedish": "sw",
        "Tamil": "ta",
        "Telugu": "te",
        "Tajik": "tg",
        "Thai": "th",
        "Tigrinya": "ti",
        "Tibetan": "bo",
        "Turkmen": "tk",
        "Tagalog": "tl",
        "Tswana": "tn",
        "Tonga": "to",
        "Turkish": "tr",
        "Tsonga": "ts",
        "Tatar": "tt",
        "Twi": "tw",
        "Tahitian": "ty",
        "Uighur": "ug",
        "Ukrainian": "uk",
        "Urdu": "ur",
        "Uzbek": "uz",
        "Venda": "ve",
        "Vietnamese": "vi",
        "Volapuk": "vo",
        "Walloon": "wa",
        "Welsh": "cy",
        "Wolof": "wo",
        "Western Frisian": "fy",
        "Xhosa": "xh",
        "Yiddish": "yi",
        "Yoruba": "yo",
        "Zhuang": "za",
        "Zulu": "zu"
    ]
    
    static let languageCode = [
        "ab": "Afar",
        "aa": "Abkhazian",
        "af": "Afrikaans",
        "ak": "Akan",
        "sq": "Albanian",
        "am": "Amharic",
        "ar": "Arabic",
        "an": "Aragonese",
        "hy": "Armenian",
        "as": "Assamese",
        "av": "Avaric",
        "ae": "Avestan",
        "ay": "Aymara",
        "az": "Azerbaijani",
        "ba": "Bashkir",
        "bm": "Bambara",
        "eu": "Basque",
        "be": "Belarusian",
        "bn": "Bengali",
        "bh": "Bihari languages",
        "bi": "Bislama",
        "bs": "Bosnian",
        "br": "Breton",
        "bg": "Bulgarian",
        "my": "Burmese",
        "ca": "Catalan; Valencian",
        "ch": "Chamorro",
        "ce": "Chechen",
        "ny": "Chichewa",
        "zh": "Chinese",
        "cv": "Chuvash",
        "kw": "Cornish",
        "co": "Corsican",
        "cr": "Cree",
        "hr": "Croatian",
        "cs": "Czech",
        "km": "Central Khmer",
        "da": "Danish",
        "dv": "Divehi",
        "nl": "Dutch",
        "dz": "Dzongkha",
        "en": "English",
        "eo": "Esperanto",
        "et": "Estonian",
        "ee": "Ewe",
        "fo": "Faroese",
        "fj": "Fijian",
        "fi": "Finish",
        "fr": "French",
        "ff": "Fulah",
        "gl": "Galician",
        "ka": "Georgian",
        "de": "German",
        "el": "Greek",
        "gn": "Guarani",
        "gu": "Gujarati",
        "lg": "Ganda",
        "ht": "Haitian",
        "ha": "Hausa",
        "he": "Hebrew",
        "hz": "Herero",
        "hi": "Hindi",
        "ho": "Hiri Motu",
        "hu": "Hungarian",
        "is": "Icelandic",
        "id": "Idonesian",
        "ig": "Igbo",
        "id": "Indonesian",
        "iu": "Inuktitut",
        "ja": "Japanese",
        "jv": "Javanese",
        "kl": "Kalaallisut",
        "kn": "Kannada",
        "kr": "Kanuri",
        "ks": "Kashmiri",
        "kk": "Kazakh",
        "ki": "Kikuyu",
        "rw": "Kinyarwanda",
        "ky": "Kirghuz",
        "kv": "Komi",
        "kg": "Kongo",
        "ko": "Korean",
        "ku": "Kurdish",
        "kj": "Kuanyama",
        "la": "Latin",
        "lb": "Luxembourgish",
        "li": "Limburgan",
        "ln": "Lingala",
        "lo": "Lao",
        "it": "Lithuanian",
        "lu": "Luba-Katanga",
        "lv": "Lavian",
        "gv": "Manx",
        "mk": "Macedonian",
        "mg": "Malagasy",
        "ms": "Malay",
        "ml": "Malayalam",
        "mt": "Maltese",
        "mi": "Maori",
        "mr": "Marathi",
        "mh": "Marshallese",
        "mn": "Mongolian",
        "na": "Naru",
        "nv": "Navajo",
        "nd": "North Ndebele",
        "ne": "Nepali",
        "ng": "Ndonga",
        "nb": "Norwegian Bokmal",
        "nn": "Norwegian Nynorsk",
        "no": "Norwegian",
        "se": "Northern Sami",
        "oc": "Occitan",
        "oj": "Ojibwa",
        "cu": "Church Slavic",
        "om": "Oromo",
        "or": "Oriya",
        "os": "Ossetian",
        "pa": "Punjabi",
        "pi": "Pali",
        "fa": "Persian",
        "pl": "Polish",
        "ps": "Pashto",
        "pt": "Portuguese",
        "qu": "Quechua",
        "rm": "Romansh",
        "rn": "Rundi",
        "ro": "Romanian",
        "ru": "Russian",
        "ii": "Sichuan Yi",
        "nr": "South Ndebele",
        "sa": "Sanskrit",
        "sc": "Sardinian",
        "sd": "Sindhi",
        "sm": "Samoan",
        "sg": "Sango",
        "sr": "Serbian",
        "sn": "Shona",
        "si": "Sinhala",
        "sk": "Slovak",
        "sl": "Slovenian",
        "so": "Somali",
        "st": "Southern Sotho",
        "es": "Spanish",
        "su": "Sundanese",
        "sw": "Swahili",
        "ss": "Swati",
        "sw": "Swedish",
        "ta": "Tamil",
        "te": "Telugu",
        "tg": "Tajik",
        "Thai": "th",
        "ti": "Tigrinya",
        "bo": "Tibetan",
        "tk": "Turkmen",
        "tl": "Tagalog",
        "tn": "Tswana",
        "to": "Tonga",
        "tr": "Turkish",
        "ts": "Tsonga",
        "tt": "Tatar",
        "tw": "Twi",
        "ty": "Tahitian",
        "ug": "Uighur",
        "uk": "Ukrainian",
        "ur": "Urdu",
        "uz": "Uzbek",
        "ve": "Venda",
        "vi": "Vietnamese",
        "vo": "Volapuk",
        "wa": "Walloon",
        "cy": "Welsh",
        "wo": "Wolof",
        "fy": "Western Frisian",
        "xh": "Xhosa",
        "yi": "Yiddish",
        "yo": "Yoruba",
        "za": "Zhuang",
        "zu": "Zulu"
    ]
}
